version: "3.7"
services:
  # https://hub.docker.com/_/rabbitmq
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/volume/data/:/var/lib/rabbitmq/
      - ./rabbitmq/volume/log/:/var/log/rabbitmq/

  # https://hub.docker.com/_/mongo
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/volume/data/:/data/db/
